package com.commute.app.data

import org.json.JSONArray
import org.json.JSONObject

private const val BACKUP_FORMAT_VERSION = 1

/** The durable, user-configured settings worth carrying across an app uninstall/reinstall —
 * not transient service state like [SettingsRepository.isAtWork]/lastSeenAt/awaySinceAt, which
 * WifiMonitorService just re-derives from live Wi-Fi presence on its next poll. */
data class BackupSettings(
    val companySsid: String?,
    val monitoringEnabled: Boolean,
    val absenceThresholdMinutes: Int,
    val lunchStartMinute: Int,
    val lunchEndMinute: Int
)

data class ParsedBackup(val settings: BackupSettings, val events: List<CommuteEvent>)

/** Serializes all commute events plus durable settings into a JSON backup file the user can
 * save anywhere (Downloads, SD card, a synced cloud folder, ...) — since it lives outside the
 * app's private storage, it survives an uninstall/reinstall that would otherwise wipe the
 * Room DB and DataStore. */
fun buildBackupJson(events: List<CommuteEvent>, settings: BackupSettings, exportedAt: Long): String {
    val root = JSONObject()
    root.put("version", BACKUP_FORMAT_VERSION)
    root.put("exportedAt", exportedAt)
    root.put(
        "settings",
        JSONObject().apply {
            put("companySsid", settings.companySsid ?: JSONObject.NULL)
            put("monitoringEnabled", settings.monitoringEnabled)
            put("absenceThresholdMinutes", settings.absenceThresholdMinutes)
            put("lunchStartMinute", settings.lunchStartMinute)
            put("lunchEndMinute", settings.lunchEndMinute)
        }
    )
    root.put(
        "events",
        JSONArray().apply {
            events.forEach { event ->
                put(
                    JSONObject().apply {
                        put("type", event.type.name)
                        put("ssid", event.ssid)
                        put("timestamp", event.timestamp)
                        put("endTimestamp", event.endTimestamp ?: JSONObject.NULL)
                    }
                )
            }
        }
    )
    return root.toString(2)
}

/** Parses a backup file written by [buildBackupJson]. Restored events always get a fresh
 * autogenerated id (the destination table is cleared before inserting, see
 * [CommuteViewModel.importBackup]), so the original row ids don't need to round-trip. */
fun parseBackupJson(json: String): ParsedBackup {
    val root = JSONObject(json)
    val settingsJson = root.getJSONObject("settings")
    val settings = BackupSettings(
        companySsid = if (settingsJson.isNull("companySsid")) null else settingsJson.optString("companySsid", "").ifBlank { null },
        monitoringEnabled = settingsJson.optBoolean("monitoringEnabled", false),
        absenceThresholdMinutes = settingsJson.optInt(
            "absenceThresholdMinutes",
            SettingsRepository.DEFAULT_ABSENCE_THRESHOLD_MINUTES
        ),
        lunchStartMinute = settingsJson.optInt("lunchStartMinute", SettingsRepository.DEFAULT_LUNCH_START_MINUTE),
        lunchEndMinute = settingsJson.optInt("lunchEndMinute", SettingsRepository.DEFAULT_LUNCH_END_MINUTE)
    )
    val eventsJson = root.getJSONArray("events")
    val events = (0 until eventsJson.length()).map { index ->
        val eventJson = eventsJson.getJSONObject(index)
        CommuteEvent(
            id = 0L,
            type = CommuteEventType.valueOf(eventJson.getString("type")),
            ssid = eventJson.getString("ssid"),
            timestamp = eventJson.getLong("timestamp"),
            endTimestamp = if (eventJson.isNull("endTimestamp")) null else eventJson.getLong("endTimestamp")
        )
    }
    return ParsedBackup(settings, events)
}
