package com.commute.app.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/** Where a [Holiday] row came from — [AUTO] rows are overwritten wholesale on every resync (see
 * [HolidayDao.deleteBySourceInRange]), while [CUSTOM] ones are only ever touched by the user, so a
 * resync can't silently erase a day someone declared a holiday by hand. */
enum class HolidaySource { AUTO, CUSTOM }

/**
 * A calendar day marked as a holiday — either synced from the public Korean holiday API or
 * declared by the user (사용자 지정 휴일). Distinct from [LeaveEntry]: a holiday doesn't consume
 * annual leave or carry a time-of-day range, it just marks the whole day for display (홈 화면 주간
 * 그래프) and future work-time-rule purposes.
 *
 * [date] is the primary key rather than an autogenerated id: at most one holiday per calendar day
 * makes sense, and using the date directly lets a resync overwrite same-day entries with
 * `OnConflictStrategy.REPLACE` instead of needing a separate lookup-then-update step.
 */
@Entity(tableName = "holidays")
data class Holiday(
    /** Local-midnight timestamp of the day (see [startOfDay]). */
    @PrimaryKey val date: Long,
    val name: String,
    val source: HolidaySource
)
